name: Chess Engine Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Stockfish
      run: |
        sudo apt update
        sudo apt install stockfish -y

    - name: Install dependencies
      run: |
        pip install python-chess

    - name: Build engine
      run: |
        make

    - name: Run automated test
      run: |
        python automation_scripts/test_git.py
